Few more sample fixes
aws-samples/aws-proton-terraform-github-actions-sample pull request #7
Opened 2022-02-01 21:42 UTC by awishn02

*Description of changes:*

* This combines `proton_run.yml` and `terraform.yml` which was adding unnecessary complexity having them be split up
* This also ensures that validation will fail the check during pull_request run
* Creates a distinction between the environment target region and the region that the resources exist in proton
* 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-02-01 21:53 UTC, awishn02 commented
ignore the failed checks, those shouldn't have run

2022-02-02 18:43 UTC, augentry requested changes

2022-02-02 18:43 UTC, augentry commented on .github/workflows/proton_run.yml
> +
nit: extra \n

2022-02-02 18:43 UTC, augentry commented on my_new_tf_env/.proton/deployment-metadata.json
> -  "deploymentId" : "c3c3759e-9227-4bf0-b18e-82de1dd7981a",
I don't think we should commit this environment, since it won't exist when the repo is cloned

2022-02-02 18:56 UTC, awishn02 commented on my_new_tf_env/.proton/deployment-metadata.json
> -  "deploymentId" : "c3c3759e-9227-4bf0-b18e-82de1dd7981a",
removed these files entirely, they don't need to be here at all since they are specific to the deployer

2022-02-02 18:56 UTC, awishn02 commented on .github/workflows/proton_run.yml
> +
fixed

2022-02-02 18:56 UTC, augentry approved these changes

2022-02-02 21:37 UTC, merged